version: '3.3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    command: --storageEngine wiredTiger
    networks: 
      - localdb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

networks: 
  localdb: 
    driver: bridge      